version : '3.6'

services :
    maildb:
        image : mysql
        container_name: db
        tty : true
	restart: always
	
        volumes:
         - ./sql-scripts:/home
        ports :
         - "3306:3306"
        environment :
         MYSQL_ROOT_PASSWORD: password
         MYSQL_DATABASE: mailserver
