version: '3.6'

services:
  dbmail:
    image: mysql
    restart: always

    environment:
      MYSQL_DATABASE: 'maildb'
      MYSQL_ROOT_PASSWORD: 'password'

    ports:
      - '3306:3306'

    expose:
      - '3306'

    volumes:
    - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    name: mysql-data
